@echo off
setlocal enabledelayedexpansion

REM ============================================================
REM shotcat - server.bat
REM One-click headless startup: brings up the full docker compose
REM stack (mysql, redis, rustfs, backend, celery-worker, front) in
REM the background so the app is reachable over the network
REM without running any local frontend dev process.
REM ============================================================

set "ROOT=%~dp0"
set "APP_DIR=%ROOT%app"
set "COMPOSE_DIR=%APP_DIR%\deploy\compose"
set "COMPOSE_FILE=%COMPOSE_DIR%\docker-compose.yml"
set "COMPOSE_ENV=%COMPOSE_DIR%\.env"

echo [server] === shotcat full stack startup ^(docker compose, headless^) ===

REM Making the stack reachable from other machines on the LAN requires
REM firewall rules and cleanup of legacy portproxy entries (containers
REM publish on internal ports; a native reverse proxy fronts the LAN).
REM That needs admin rights.
net session >nul 2>&1
if errorlevel 1 (
    echo [server] this script needs Administrator rights to open the LAN-facing ports. Right-click server.bat and choose "Run as administrator".
    goto :end
)

if not exist "%COMPOSE_ENV%" (
    echo [server] %COMPOSE_ENV% not found. Run install.bat first.
    goto :end
)

REM Read the actual published ports from .env. These are deliberately
REM different from test.bat/run.bat's native dev ports (8000/7788) so the
REM two modes can never fight over the same port.
for /f "usebackq tokens=1,2 delims==" %%A in ("%COMPOSE_ENV%") do (
    set "key=%%A"
    if not "!key:~0,1!"=="#" if not "%%A"=="" set "%%A=%%B"
)
if not defined SERVER_BACKEND_PORT set "SERVER_BACKEND_PORT=18000"
if not defined SERVER_FRONT_PORT set "SERVER_FRONT_PORT=18080"
REM Internal ports: what the containers publish on 127.0.0.1. These MUST
REM differ from the public ports above -- WSL2 mirrored networking tracks
REM bound ports machine-wide by port number, and reusing the same number
REM for the portproxy listener makes LAN-facing connections get refused.
if not defined SERVER_BACKEND_INTERNAL_PORT set "SERVER_BACKEND_INTERNAL_PORT=28000"
if not defined SERVER_FRONT_INTERNAL_PORT set "SERVER_FRONT_INTERNAL_PORT=28080"

REM Docker Desktop is not allowed here; the stack runs via Docker Engine
REM inside WSL2 (set up by install.bat).
for /f "delims=" %%W in ('wsl -- wslpath -a "%ROOT:~0,-1%"') do set "WSL_ROOT=%%W"
set "WSL_COMPOSE_DIR=%WSL_ROOT%/app/deploy/compose"
set "WSL_COMPOSE_ENV=%WSL_COMPOSE_DIR%/.env"
set "WSL_COMPOSE_FILE=%WSL_COMPOSE_DIR%/docker-compose.yml"
set "DOCKER=wsl -- docker"

%DOCKER% compose --env-file "%WSL_COMPOSE_ENV%" -f "%WSL_COMPOSE_FILE%" up -d --build
if errorlevel 1 (
    echo [server] docker compose up failed
    goto :end
)

REM LAN access design: a user-mode native reverse proxy (Caddy, single
REM exe at tools\caddy.exe) listens on the public ports and forwards into
REM WSL2, so the WSL network never faces the LAN interface directly. The
REM forward target depends on the WSL networking mode:
REM   - NAT (recommended for LAN-serving machines): the WSL internal IP.
REM   - mirrored (fine for localhost-only dev): 127.0.0.1.
REM Why Caddy and not netsh portproxy: the iphlpsvc kernel relay poisons
REM WinNAT state when piping LAN-originated connections into the WSL NAT
REM subnet (first request succeeds, later ones get RST), while a
REM user-mode native listener is stable on the exact same path. Note the
REM host's localhostForwarding is also broken on some machines, so under
REM NAT the target must be the WSL IP, never 127.0.0.1.
set "CONNECT_ADDR=127.0.0.1"
set "WSL_NET_MODE=unknown"
for /f "delims=" %%M in ('wsl -- wslinfo --networking-mode 2^>nul') do set "WSL_NET_MODE=%%M"
if /i "!WSL_NET_MODE!"=="nat" (
    for /f "tokens=1" %%I in ('wsl -- hostname -I') do set "CONNECT_ADDR=%%I"
)
echo [server] WSL networking mode: !WSL_NET_MODE!, forward target: !CONNECT_ADDR!

if not exist "%ROOT%tools\caddy.exe" (
    echo [server] tools\caddy.exe not found -- it is the LAN-facing reverse proxy.
    echo [server] Download the Windows amd64 build from:
    echo [server]     https://caddyserver.com/api/download?os=windows^&arch=amd64
    echo [server] rename it to caddy.exe, put it at %ROOT%tools\caddy.exe and re-run server.bat.
    goto :end
)

REM Legacy cleanup (earlier versions used netsh portproxy on these ports),
REM plus the firewall openings for the public ports.
for %%P in (!SERVER_FRONT_PORT! !SERVER_BACKEND_PORT!) do (
    netsh interface portproxy delete v4tov4 listenaddress=0.0.0.0 listenport=%%P >nul 2>&1
    netsh advfirewall firewall show rule name="shotcat-server-%%P" >nul 2>&1
    if errorlevel 1 (
        netsh advfirewall firewall add rule name="shotcat-server-%%P" dir=in action=allow protocol=TCP localport=%%P >nul
    )
)

set "CADDYFILE=%TEMP%\shotcat-caddyfile"
> "%CADDYFILE%" echo # generated by server.bat -- do not edit
>>"%CADDYFILE%" echo {
>>"%CADDYFILE%" echo     auto_https off
>>"%CADDYFILE%" echo     admin off
>>"%CADDYFILE%" echo }
>>"%CADDYFILE%" echo :!SERVER_FRONT_PORT! {
>>"%CADDYFILE%" echo     reverse_proxy !CONNECT_ADDR!:!SERVER_FRONT_INTERNAL_PORT!
>>"%CADDYFILE%" echo }
>>"%CADDYFILE%" echo :!SERVER_BACKEND_PORT! {
>>"%CADDYFILE%" echo     reverse_proxy !CONNECT_ADDR!:!SERVER_BACKEND_INTERNAL_PORT!
>>"%CADDYFILE%" echo }

echo [server] starting the LAN-facing reverse proxy ^(caddy^) in window "shotcat-caddy"...
taskkill /FI "WINDOWTITLE eq shotcat-caddy" /T /F >nul 2>&1
start "shotcat-caddy" /min "%ROOT%tools\caddy.exe" run --config "%CADDYFILE%" --adapter caddyfile

REM Self-check: probe each hop so a broken link is visible immediately
REM instead of being discovered later from another machine. Any HTTP
REM status (even 404) counts as OK -- only 000 means the connection failed.
set "SELFCHECK_FAIL="
echo [server] self-check 1/2: containers on internal ports ^(via !CONNECT_ADDR!^)...
for %%P in (!SERVER_FRONT_INTERNAL_PORT! !SERVER_BACKEND_INTERNAL_PORT!) do call :probe_port !CONNECT_ADDR! %%P
echo [server] self-check 2/2: full chain through the reverse proxy...
for %%P in (!SERVER_FRONT_PORT! !SERVER_BACKEND_PORT!) do call :probe_port 127.0.0.1 %%P

if defined SELFCHECK_FAIL (
    echo [server] === stack started but the self-check FAILED, LAN access will not work until this is fixed ===
    goto :end
)
echo [server] === full stack is up, self-check passed ===
echo [server] frontend ^(built^): http://localhost:%SERVER_FRONT_PORT%
echo [server] backend docs: http://localhost:%SERVER_BACKEND_PORT%/docs
echo [server] other machines on the same network can reach it via this host's LAN IP on the same ports.

:end
endlocal
pause
goto :eof

REM Probe host %1 port %2 over HTTP, retrying for up to ~30s: nginx answers
REM the moment its container starts, but the backend needs several seconds
REM to connect to MySQL and begin listening, so a single immediate probe
REM produces false FAILs. Any HTTP status (even 404) counts as reachable.
:probe_port
set "HTTP_CODE=000"
set /a PROBE_TRIES=0
:probe_retry
for /f %%C in ('curl -s -o NUL -m 5 -w "%%{http_code}" http://%~1:%~2/ 2^>nul') do set "HTTP_CODE=%%C"
if not "%HTTP_CODE%"=="000" (
    echo [server][OK] http://%~1:%~2/ responded ^(HTTP %HTTP_CODE%^)
    exit /b 0
)
set /a PROBE_TRIES+=1
if %PROBE_TRIES%==1 echo [server] waiting for http://%~1:%~2/ to come up...
if %PROBE_TRIES% LSS 15 (
    timeout /t 2 /nobreak >nul
    goto probe_retry
)
echo [server][FAIL] http://%~1:%~2/ still unreachable after ~30s. Container status:
wsl -- docker ps --format "table {{.Names}}\t{{.Status}}"
set "SELFCHECK_FAIL=1"
exit /b 1
